---
title: "Storm Surge in Norfolk VA"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: sandstone
---

```{r setup, include=FALSE}
library(flexdashboard)
library(leaflet)
library(leafem)
library(mapview)
library(sf)
library(leafpop)
setwd("C:/Users/yungz/Desktop/Ben R/R Projects/Leaflet and Shiny/Norfolk Storm Surge")
load(".RData")
```

```{r echo=FALSE, message=FALSE}
# setting the base mapview called m1
m1 <-mapview(`Category 4`,col.region = "gray", popup = NULL, 
             label = FALSE, homebutton = FALSE, alpha.regions=.6)+
  mapview(`Category 3`,col.region = "yellow", popup = NULL, 
          label = FALSE, homebutton = FALSE, alpha.regions=.4)+
  mapview(`Category 2`,col.region = "green", popup = NULL, 
          label = FALSE, homebutton = FALSE, alpha.regions=.5)+
  mapview(`Category 1`,col.region = "blue", popup = NULL, 
          label = FALSE, homebutton = FALSE, alpha.regions=.6)
```

```{r echo=FALSE, message=FALSE}
# creating a dataframe of long/lats for nearby points
places <- c("Naval Station Norfolk")
lon <- c(-76.296478)
lat <- c(36.936858)

`Naval Station Norfolk` <-data.frame(places, lat, lon)
`Naval Station Norfolk` <- st_as_sf(points, coords = c("lon", "lat"), crs = 4326)

img <- "https://upload.wikimedia.org/wikipedia/commons/d/d2/Naval_Station_Norfolk.jpg"
```

```{r}
m1+mapview(`Naval Station Norfolk`, label = FALSE, popup = popupImage(img, src = "remote"), col.region = "black")
```
